export interface CategoryFilterItem {
  name: string;
  slug: string;
}

export interface ColorFilterItem {
  name: string;
  hex: string;
}

export interface ProductItem {
  id: number;
  name: string;
  price: number;
  originalPrice?: number;
  rating: number;
  reviews: number;
  image: string;
  badge?: "new" | "bestSeller" | "hotTiktok" | "sale" | "limited" | "soldOut";
  badgeLabel?: string;
  category: string;
  color: string;
  tags: string[];
}

export const CATEGORY_FILTERS: CategoryFilterItem[] = [
  { name: "Động vật dễ thương", slug: "moc-khoa-dong-vat" },
  { name: "Hoa len", slug: "hoa-len" },
  { name: "Gấu bông len", slug: "gau-bong-len" },
  { name: "Túi len handmade", slug: "tui-len-handmade" },
  { name: "Quà sinh nhật", slug: "qua-sinh-nhat" },
  { name: "Quà tặng theo yêu cầu", slug: "qua-tang-theo-yeu-cau" },
];

export const COLOR_FILTERS: ColorFilterItem[] = [
  { name: "Xanh", hex: "#3B82F6" },
  { name: "Đỏ", hex: "#EF4444" },
  { name: "Vàng", hex: "#F59E0B" },
  { name: "Cam", hex: "#F97316" },
  { name: "Đen", hex: "#111827" },
  { name: "Tím", hex: "#8B5CF6" },
  { name: "Hồng", hex: "#F9B4C7" },
  { name: "Trắng", hex: "#FFFFFF" },
  { name: "Nâu", hex: "#78350F" },
  { name: "Kem", hex: "#FEF3C7" },
];

export const SUGGESTED_TAGS: string[] = [
  "Móc khóa treo balo",
  "Quà sinh nhật",
  "Tặng người yêu",
];

export const CATALOG_PRODUCTS: ProductItem[] = [
  {
    id: 1,
    name: "Móc khóa Cún bông len handmade",
    price: 99000,
    originalPrice: 120000,
    rating: 5,
    reviews: 24,
    image: "/images/products/moc-khoa-cun.png",
    badge: "hotTiktok",
    badgeLabel: "Hot TikTok",
    category: "moc-khoa-dong-vat",
    color: "Nâu",
    tags: ["Móc khóa treo balo"],
  },
  {
    id: 2,
    name: "Móc khóa Mèo con len đáng yêu",
    price: 89000,
    rating: 4.8,
    reviews: 18,
    image: "/images/products/moc-khoa-meo.png",
    badge: "new",
    badgeLabel: "Mới",
    category: "moc-khoa-dong-vat",
    color: "Hồng",
    tags: ["Móc khóa treo balo"],
  },
  {
    id: 3,
    name: "Móc khóa Ếch xanh tinh nghịch",
    price: 79000,
    originalPrice: 95000,
    rating: 4.9,
    reviews: 32,
    image: "/images/products/moc-khoa-ech.png",
    badge: "sale",
    badgeLabel: "Sale -17%",
    category: "moc-khoa-dong-vat",
    color: "Xanh",
    tags: ["Móc khóa treo balo"],
  },
  {
    id: 4,
    name: "Móc khóa Gấu béo đan len",
    price: 89000,
    rating: 5,
    reviews: 40,
    image: "/images/products/moc-khoa-gau.png",
    badge: "bestSeller",
    badgeLabel: "Bán chạy",
    category: "moc-khoa-dong-vat",
    color: "Nâu",
    tags: ["Móc khóa treo balo", "Tặng người yêu"],
  },
  {
    id: 5,
    name: "Chậu hoa Hướng Dương len trang trí",
    price: 189000,
    originalPrice: 220000,
    rating: 4.7,
    reviews: 15,
    image: "/images/products/binh-hoa-huong-duong.png",
    badge: "hotTiktok",
    badgeLabel: "Hot TikTok",
    category: "hoa-len",
    color: "Vàng",
    tags: ["Quà sinh nhật"],
  },
  {
    id: 6,
    name: "Bình hoa Tulip len handmade",
    price: 159000,
    rating: 4.9,
    reviews: 21,
    image: "/images/products/binh-hoa-tulip.png",
    category: "hoa-len",
    color: "Hồng",
    tags: ["Quà sinh nhật", "Tặng người yêu"],
  },
  {
    id: 7,
    name: "Gấu bông Thỏ len trắng đáng yêu",
    price: 249000,
    originalPrice: 299000,
    rating: 5,
    reviews: 12,
    image: "/images/products/gau-bong-tho.png",
    badge: "limited",
    badgeLabel: "Giới hạn",
    category: "gau-bong-len",
    color: "Trắng",
    tags: ["Quà sinh nhật", "Tặng người yêu"],
  },
  {
    id: 8,
    name: "Túi len Handmade hoa cúc nổi",
    price: 199000,
    rating: 4.8,
    reviews: 9,
    image: "/images/products/tui-hoa-cuc.png",
    category: "tui-len-handmade",
    color: "Vàng",
    tags: ["Tặng người yêu"],
  },
  {
    id: 9,
    name: "Móc khóa Heo hồng len tròn",
    price: 85000,
    rating: 4.9,
    reviews: 27,
    image: "/images/products/moc-khoa-meo.png",
    category: "moc-khoa-dong-vat",
    color: "Hồng",
    tags: ["Móc khóa treo balo"],
  },
  {
    id: 10,
    name: "Cành Hoa Tulip len đơn lẻ",
    price: 49000,
    originalPrice: 60000,
    rating: 4.6,
    reviews: 45,
    image: "/images/products/hoa-tulip.png",
    badge: "sale",
    badgeLabel: "Sale -18%",
    category: "hoa-len",
    color: "Đỏ",
    tags: ["Quà sinh nhật"],
  },
  {
    id: 11,
    name: "Móc khóa Cú mèo len handmade",
    price: 95000,
    rating: 5,
    reviews: 16,
    image: "/images/products/moc-khoa-gau.png",
    category: "moc-khoa-dong-vat",
    color: "Tím",
    tags: ["Móc khóa treo balo"],
  },
  {
    id: 12,
    name: "Bó hoa Tulip len đủ màu",
    price: 289000,
    rating: 4.9,
    reviews: 14,
    image: "/images/products/binh-hoa-tulip.png",
    category: "hoa-len",
    color: "Kem",
    tags: ["Quà sinh nhật", "Tặng người yêu"],
  },
  {
    id: 13,
    name: "Móc khóa Khủng long xanh đan len",
    price: 99000,
    rating: 4.8,
    reviews: 19,
    image: "/images/products/moc-khoa-ech.png",
    category: "moc-khoa-dong-vat",
    color: "Xanh",
    tags: ["Móc khóa treo balo"],
  },
  {
    id: 14,
    name: "Gấu bông Cún xù đan len mềm",
    price: 220000,
    rating: 5,
    reviews: 11,
    image: "/images/products/moc-khoa-cun.png",
    category: "gau-bong-len",
    color: "Kem",
    tags: ["Quà sinh nhật"],
  },
  {
    id: 15,
    name: "Túi tỏi len handmade cho bé",
    price: 69000,
    rating: 4.7,
    reviews: 38,
    image: "/images/products/tui-hoa-cuc.png",
    category: "tui-len-handmade",
    color: "Cam",
    tags: ["Quà sinh nhật"],
  },
  {
    id: 16,
    name: "Móc khóa Thỏ ngọc hồng xinh",
    price: 89000,
    rating: 4.9,
    reviews: 23,
    image: "/images/products/gau-bong-tho.png",
    category: "moc-khoa-dong-vat",
    color: "Hồng",
    tags: ["Móc khóa treo balo"],
  },
  {
    id: 17,
    name: "Chậu Cây Xương Rồng len nhỏ",
    price: 119000,
    rating: 4.8,
    reviews: 8,
    image: "/images/products/binh-hoa-huong-duong.png",
    category: "hoa-len",
    color: "Xanh",
    tags: ["Quà sinh nhật"],
  },
  {
    id: 18,
    name: "Móc khóa Gấu Pooh len dễ thương",
    price: 99000,
    rating: 5,
    reviews: 15,
    image: "/images/products/moc-khoa-gau.png",
    category: "moc-khoa-dong-vat",
    color: "Vàng",
    tags: ["Móc khóa treo balo"],
  },
  {
    id: 19,
    name: "Túi đeo chéo len hình thú",
    price: 179000,
    rating: 4.6,
    reviews: 6,
    image: "/images/products/tui-hoa-cuc.png",
    category: "tui-len-handmade",
    color: "Nâu",
    tags: ["Quà sinh nhật"],
  },
  {
    id: 20,
    name: "Bình hoa Hướng Dương mini đan len",
    price: 139000,
    rating: 4.9,
    reviews: 10,
    image: "/images/products/binh-hoa-huong-duong.png",
    category: "hoa-len",
    color: "Vàng",
    tags: ["Quà sinh nhật"],
  },
  {
    id: 21,
    name: "Móc khóa Bạch tuộc cảm xúc len",
    price: 59000,
    rating: 4.8,
    reviews: 52,
    image: "/images/products/moc-khoa-ech.png",
    category: "moc-khoa-dong-vat",
    color: "Tím",
    tags: ["Móc khóa treo balo"],
  },
  {
    id: 22,
    name: "Móc khóa Cà rốt cam nhỏ nhắn",
    price: 39000,
    rating: 4.7,
    reviews: 29,
    image: "/images/products/hoa-tulip.png",
    category: "moc-khoa-dong-vat",
    color: "Cam",
    tags: ["Móc khóa treo balo"],
  },
  {
    id: 23,
    name: "Bó hoa Tulip len 3 bông rực rỡ",
    price: 179000,
    rating: 5,
    reviews: 7,
    image: "/images/products/binh-hoa-tulip.png",
    category: "hoa-len",
    color: "Đỏ",
    tags: ["Quà sinh nhật", "Tặng người yêu"],
  },
  {
    id: 24,
    name: "Móc khóa Bé Bơ sáp đan len",
    price: 79000,
    rating: 4.9,
    reviews: 14,
    image: "/images/products/moc-khoa-ech.png",
    category: "moc-khoa-dong-vat",
    color: "Xanh",
    tags: ["Móc khóa treo balo"],
  },
];
